name: Deploy Project 9 Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-north-1

      # 3️⃣ Zip the Lambda function
      - name: Zip Lambda function
        run: |
          zip -r lambda_function.zip lambda_function.py

      # 4️⃣ Deploy Lambda using AWS CLI
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name Project9LambdaDemo \
            --zip-file fileb://lambda_function.zip
